name: Pull request
on:
  pull_request:

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - run: echo "pull_number=${{ github.event.number }}" >> $GITHUB_ENV
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
          SLACK_CHANNEL: githubpullrequests
          SLACK_MESSAGE: 'Please review on https://github.com/GlobetrekkerChallenge/wellteq-api-docker-deployment/pull/${{ env.pull_number}}'
          SLACK_TITLE: 'Pull request for Wellteq API Docker Deployment'
          SLACK_USERNAME: 'Wellteq'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
